"""Update users table. Add: first_name, last_name

Revision ID: 83c5f55ea77c
Revises: 1fe0d16f449b
Create Date: 2025-09-11 22:09:29.536644

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '83c5f55ea77c'
down_revision: str | Sequence[str] | None = '1fe0d16f449b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('first_name', sa.String(length=50), nullable=True)
    )
    op.add_column(
        'users', sa.Column('last_name', sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
