"""update tables

Revision ID: 8b67f9b59d85
Revises: c1eff65b0b66
Create Date: 2025-09-11 00:56:56.088396

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8b67f9b59d85'
down_revision: str | Sequence[str] | None = 'c1eff65b0b66'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'events', sa.Column('owner', sa.String(length=50), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'owner')
    # ### end Alembic commands ###
