"""update communications

Revision ID: 945c65ccb642
Revises: 11cbe42b9621
Create Date: 2025-09-11 18:57:38.406455

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '945c65ccb642'
down_revision: str | Sequence[str] | None = '11cbe42b9621'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('chat_id'),
    )
    op.create_table(
        'events',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'event_type', sa.Enum('BIRTHDAY', name='eventtype'), nullable=False
        ),
        sa.Column('event_date', sa.Date(), nullable=False),
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column('owner', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ['chat_id'],
            ['users.chat_id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('users')
    # ### end Alembic commands ###
